### ISSUE TITLE
[Frontend] No AST variables gives a string instead of an array

### ISSUE THREAD

**Issue by Siilwyn** [QuTech-Delft/libqasm#251]
When the AST has no variables in the `Program` root we expect `variables` to an empty array `[]`. Instead a string is given containing an empty array: `"[]"`.

(Using `analyze_string_to_json`).

**Comment by Siilwyn** [comment]
Just realized there is a newer version, we are using v0.6.6 but unsure if we'll have to time to update. That said, this issue could be fixed.

**Comment by rturrado** [comment]
Thanks for opening the issue, @Siilwyn! I'll have a look at it.

**Comment by rturrado** [comment]
This bug should be fixed in libqasm/0.6.8.
