### ISSUE TITLE
Python usage of libqasm

### ISSUE THREAD

**Issue by Astlaan** [QuTech-Delft/libqasm#89]
Hello!

I was wondering how I could use libqasm to get the a QASM circuit in a python data structure which I could access and operate on.

I tried:

`
from libQasm import libQasm as lq

a = lq("./test/bell.qasm") #while on the qasm_flex_bison folder
b = a.getQasmRepresentation()
`

So far so good.
But they I try to access it's methods, like numQubits, etc I can't:
`b.numQubits()` doesn't work, for example... The only attributes of 'b' appear to be:
`b.acquire(  b.append(   b.disown(   b.next(     b.own(`

Any ideas?

**Comment by imranashraf** [comment]
@Astlaan the python interface is primarily meant for using libqasm for automated unit testing in compiler (openql) rather than giving access to the attributes as you mentioned.

**Comment by kel85uk** [comment]
@Astlaan Indeed it was made as @imranashraf mentioned. It would be a very nice extension to the library if we can have the AST in python too.

**Comment by koffie** [comment]
Of course if you would want to analyse an actual cqasm file then you should use  `a.analyze_file` instead.
